plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
        content {
            includeGroup("fuzs.forgeconfigapiport")
        }
    }
}

dependencies {
    implementation("fuzs.forgeconfigapiport:forgeconfigapiport-common:${fcap_version}") { transitive = false }

    api("org.jetbrains.kotlin:kotlin-reflect")
    compileOnly("org.jetbrains:annotations:24.1.0")

    implementation('com.electronwill.night-config:core:3.8.0')
    implementation('com.electronwill.night-config:toml:3.8.0')
    implementation('com.electronwill.night-config:json:3.8.0')
}