version=1.0.0
group=dev.wren.truss
java_version=21


mod_name=Truss
mod_author=wren
mod_id=truss
license=GPL-3.0
credits=
description=The description of your mod. \nAccepts multilines.
sources=https://github.com/whimsicalwren/truss
issue_tracker=https://github.com/whimsicalwren/truss/issues

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10
mc_log4j2_version=2.22.1
fcap_version=9.1.2

fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

forge_version=52.0.28
forge_loader_version_range=[52,)

neoforge_version=21.1.80
neoforge_loader_version_range=[4,)
# same for both forge and neoforge
kff_version=5.12.0
kff_version_range=[5.4,)
fabric_kotlin_version=1.11.0+kotlin.2.0.0

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
