// core/build.gradle
plugins {
    id 'java-library'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

configurations {
    coreJava {
        canBeResolved = false
        canBeConsumed = true
    }
    coreResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    coreJava sourceSets.main.java.sourceDirectories.singleFile
    coreResources sourceSets.main.resources.sourceDirectories.singleFile
}