plugins {
    id 'multiloader-core'
}

configurations {
    coreJava {
        canBeResolved = false
        canBeConsumed = true
    }
    coreResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    implementation("org.apache.logging.log4j:log4j-api:${mc_log4j2_version}")
}

artifacts {
    coreJava sourceSets.main.java.sourceDirectories.singleFile
    coreResources sourceSets.main.resources.sourceDirectories.singleFile
}