plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    id 'org.jetbrains.kotlin.kapt'
}

configurations {
    coreJava {
        canBeResolved = true
        canBeConsumed = false
    }
    coreKotlin {
        canBeResolved = true
        canBeConsumed = false
    }
    coreResources {
        canBeResolved = true
        canBeConsumed = false
    }
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonKotlin {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}


neoForge {
    neoFormVersion = neo_form_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

    compileOnly project(':core')
    coreJava project(path: ':core', configuration: 'coreJava')
    coreKotlin project(path: ':core', configuration: 'coreKotlin')
    coreResources project(path: ':core', configuration: 'coreResources')
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.coreJava)
    source(configurations.coreJava)
}

tasks.named('compileKotlin') {
    dependsOn(configurations.coreKotlin)
    source(configurations.coreKotlin)
}

processResources {
    dependsOn(configurations.coreResources)
    from(configurations.coreResources)
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.files
    commonKotlin sourceSets.main.kotlin.sourceDirectories.files
    commonResources sourceSets.main.resources.sourceDirectories.files
}


